using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Text.RegularExpressions;

namespace checkavlist
{
	class Program
	{
		static void Main(string[] args)
		{
			Tasklist();
		}


		public static void Tasklist()
		{
			Process p = new Process();
			//设置要启动的应用程序
			p.StartInfo.FileName = "cmd.exe";
			//是否使用操作系统shell启动
			p.StartInfo.UseShellExecute = false;
			// 接受来自调用程序的输入信息
			p.StartInfo.RedirectStandardInput = true;
			//输出信息
			p.StartInfo.RedirectStandardOutput = true;
			// 输出错误
			p.StartInfo.RedirectStandardError = true;
			//不显示程序窗口
			p.StartInfo.CreateNoWindow = true;
			//启动程序
			p.Start();

			//向cmd窗口发送输入信息
			p.StandardInput.WriteLine("tasklist /svc" + "&exit");

			p.StandardInput.AutoFlush = true;

			//获取输出信息
			string strOuput = p.StandardOutput.ReadToEnd();
			//等待程序执行完退出进程
			p.WaitForExit();
			p.Close();

			string pattern2 = @"(.*?)exe\s*?\d+";
			foreach (Match match in Regex.Matches(strOuput, pattern2))
			{
				string name = match.Value.Split(' ')[0];
				string pid = match.Value.Replace("exe", "@").Split('@')[1].Trim();

				check(name, pid);
			}
		}


		public static void check(string name, string pid)
		{
				if (avlist.ContainsKey(name))
				{
					Console.WriteLine("{0} {1} {2}", name, pid, avlist[name]);
				}
		}

		public static Dictionary<string, string> avlist = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) {
			{"360rp.exe", "360杀毒"},
	{"360safe.exe", "360安全卫士-主程序"},
	{"360safebox.exe", "360杀毒"},
	{"360sd.exe", "360杀毒"},
	{"360tray.exe", "360安全卫士-实时保护"},
	{"_avp32.exe", "卡巴斯基"},
	{"_avpcc.exe", "卡巴斯基"},
	{"_avpm.exe", "卡巴斯基"},
	{"A2CMD.exe", "Emsisoft Anti-Malware"},
	{"A2FREE.exe", "a-squared Free"},
	{"a2guard.exe", "a-squared杀毒"},
	{"A2SERVICE.exe", "a-squared free"},
	{"aAvgApi.exe", "AVG"},
	{"ackwin32.exe", "已知杀软进程,名称暂未收录"},
	{"ad-watch.exe", "Lavasoft杀毒"},
	{"adam.exe", "绿鹰安全精灵"},
	{"ADVCHK.exe", "Norton AntiVirus"},
	{"afwServ.exe", " Avast Antivirus "},
	{"AGB.exe", "安天防线"},
	{"AHPROCMONSERVER.exe", "安天防线"},
	{"AIRDEFENSE.exe", "AirDefense"},
	{"ALERTSVC.exe", "Norton AntiVirus"},
	{"alogserv.exe", "McAfee VirusScan"},
	{"AMON.exe", "Tiny Personal Firewall"},
	{"ananwidget.exe", "墨者安全专家"},
	{"anti-trojan.exe", "Anti-Trojan Elite"},
	{"ANTIVIR.exe", "已知杀软进程,名称暂未收录"},
	{"APVXDWIN.exe", "熊猫卫士"},
	{"ArcaTasksService.exe", "ArcaVir杀毒"},
	{"arr.exe", "Application Request Route"},
	{"ashDisp.exe", "Avast网络安全"},
	{"ASHMAISV.exe", "Alwil"},
	{"ASHSERV.exe", "Avast Anti-virus"},
	{"ASHSIMPL.exe", "AVAST!VirusCleaner"},
	{"ASHWEBSV.exe", "Avast"},
	{"AST.exe", "超级巡警"},
	{"ASWSCAN.exe", "Avast"},
	{"ASWUPDSV.exe", "Avast"},
	{"atguard.exe", "AntiVir"},
	{"atupdater.exe", "已知杀软进程,名称暂未收录"},
	{"atwatch.exe", "Mustek"},
	{"au.exe", "NSIS"},
	{"aupdate.exe", "Symantec"},
	{"auto-protect.nav80try.exe", "已知杀软进程,名称暂未收录"},
	{"autodown.exe", "AntiVirus AutoUpdater"},
	{"AvastUI.exe", "Avast!5主程序"},
	{"avcenter.exe", "Avira(小红伞)"},
	{"AVCIMAN.exe", "熊猫卫士"},
	{"AVCONSOL.exe", "McAfee"},
	{"AVENGINE.exe", "熊猫卫士"},
	{"AVESVC.exe", "Avira AntiVir Security Service"},
	{"AVEVL32.exe", "已知杀软进程,名称暂未收录"},
	{"avg.exe", "AVG Anti-Virus"},
	{"AVGAM.exe", "AVG"},
	{"avgaurd.exe", "Avira Antivir"},
	{"AVGCC.exe", "AVG"},
	{"AVGCC32.exe", "AVG"},
	{"AVGCHSVX.exe", "AVG"},
	{"AVGCSRVX", "AVG"},
	{"AVGCTRL.exe", "AVG"},
	{"AVGEMC.exe", "AVG"},
	{"AVGFWSRV.exe", "AVG"},
	{"AVGNSX.exe", "AVG"},
	{"avgnt.exe", "Avira(小红伞)"},
	{"AVGNTMGR.exe", "AVG"},
	{"avgrsx.exe", "AVG"},
	{"AVGSERV.exe", "AVG"},
	{"avgserv9.exe", "AVG"},
	{"AVGTRAY.exe", "AVG"},
	{"avguard.exe", "Avira(小红伞)"},
	{"AVGUPSVC.exe", "AVG"},
	{"avgw.exe", "AVG"},
	{"avgwdsvc.exe", "AVG杀毒"},
	{"AVINITNT.exe", "Command AntiVirus for NT Server"},
	{"AVIRA.exe", "小红伞杀毒"},
	{"AVK.exe", "AntiVirusKit"},
	{"avkpop.exe", "G DATA SOFTWARE AG"},
	{"avkserv.exe", "G DATA SOFTWARE AG"},
	{"avkservice.exe", "G DATA SOFTWARE AG"},
	{"avkwctl9.exe", "G DATA SOFTWARE AG"},
	{"avltmain.exe", "Panda Software Aplication"},
	{"avnt.exe", "H+BEDV Datentechnik GmbH"},
	{"avp.exe", "Kaspersky"},
	{"avp32.exe", "Kaspersky Anti-Virus"},
	{"AVPCC.exe", "Kaspersky"},
	{"avpdos32.exe", " Kaspersky AntiVirus"},
	{"AVPM.exe", "Kaspersky"},
	{"avptc32.exe", " Kaspersky AntiVirus"},
	{"avpupd.exe", " Kaspersky AntiVirus"},
	{"AVSCHED32.exe", "H+BEDV"},
	{"AVSERVER.exe", "Kerio MailServer"},
	{"AVSYNMGR.exe", "McAfee"},
	{"AVWatchService.exe", "VIRUSfighter杀毒"},
	{"avwin.exe", " H+BEDV"},
	{"AVWUPSRV.exe", "H+BEDV"},
	{"AVZ.exe", "AVZ"},
	{"baiduansvx.exe", "百度卫士-主进程"},
	{"BaiduSd.exe", "百度杀毒-主程序"},
	{"BaiduSdSvc.exe", "百度杀毒-服务进程"},
	{"BaiduSdTray.exe", "百度杀毒-托盘进程"},
	{"bargains.exe", "Exact Advertising SpyWare"},
	{"bddownloader.exe", "百度卫士"},
	{"BDSWITCH.exe", "BitDefender Module"},
	{"beagle.exe", "Avast"},
	{"beikesan.exe", "贝壳云安全"},
	{"BKavService.exe", "Bkav杀毒"},
	{"BLACKD.exe", "BlackICE"},
	{"blackice.exe", "BlackICE"},
	{"blink.exe", "micromedia"},
	{"blss.exe", "CBlaster"},
	{"bootwarn.exe", "Symantec"},
	{"bpc.exe", "Grokster"},
	{"brasil.exe", "Exact Advertising"},
	{"ccapp.exe", "SymantecNorton"},
	{"CCEVTMGR.exe", "Symantec"},
	{"ccRegVfy.exe", "Norton杀毒软件"},
	{"ccSetMgr.exe", "赛门铁克"},
	{"ccSvcHst.exe", "Norton杀毒"},
	{"cdp.exe", "CyberLink Corp."},
	{"cfd.exe", "Motive Communications"},
	{"cfgwiz.exe", " Norton AntiVirus"},
	{"CFP.exe", "COMODO"},
	{"CKSoftShiedAntivirus4.exe", "Shield Antivirus杀毒"},
	{"CLAMWIN.exe", "ClamWin Portable"},
	{"claw95.exe", "已知杀软进程,名称暂未收录"},
	{"claw95cf.exe", "已知杀软进程,名称暂未收录"},
	{"clean.exe", "windows流氓软件清理大师"},
	{"cleaner.exe", "windows流氓软件清理大师"},
	{"cleaner3.exe", "windows流氓软件清理大师"},
	{"cleaner8.exe", "The Cleaner杀毒"},
	{"cleanpc.exe", "windows流氓软件清理大师"},
	{"cleanup.exe", "McAfee"},
	{"CMCTrayIcon.exe", "CMC杀毒"},
	{"cmdagent.exe", "McAfee"},
	{"CorantiControlCenter32.exe", "Coranti2012杀毒"},
	{"cpd.exe", "McAfee"},
	{"cpf.exe", "Comodo"},
	{"ctrl.exe", "已知杀软进程,名称暂未收录"},
	{"CUREIT.exe", "DrWeb CureIT"},
	{"cv.exe", "已知杀软进程,名称暂未收录"},
	{"d_manage.exe", "D盾"},
	{"D_Safe_Manage.exe", "D盾"},
	{"defalert.exe", "Symantec"},
	{"DEFENDERDAEMON.exe", "ShadowDefender"},
	{"defscangui.exe", "Symantec"},
	{"DEFWATCH.exe", "Norton Antivirus"},
	{"doors.exe", "已知杀软进程,名称暂未收录"},
	{"dpf.exe", "已知杀软进程,名称暂未收录"},
	{"dpps2.exe", "PanicWare"},
	{"DRWADINS.exe", "Dr.Web"},
	{"DRWEB.exe", "Dr.Web"},
	{"dssagent.exe", "Broderbund"},
	{"ecengine.exe", "已知杀软进程,名称暂未收录"},
	{"egui.exe", "ESET NOD32"},
	{"eguiProxy.exe", "ESET NOD32"},
	{"ekrn.exe", "ESET NOD32"},
	{"emet_agent.exe", "EMET"},
	{"emet_service.exe", "EMET"},
	{"emsw.exe", "Alset Inc"},
	{"engineserver.exe", "McAfee"},
	{"ent.exe", "已知杀软进程,名称暂未收录"},
	{"espwatch.exe", "已知杀软进程,名称暂未收录"},
	{"ethereal.exe", "RationalClearCase"},
	{"EWIDOCTRL.exe", "Ewido Security Suite"},
	{"exe.avxw.exe", "已知杀软进程,名称暂未收录"},
	{"expert.exe", "已知杀软进程,名称暂未收录"},
	{"EZANTIVIRUSREGISTRATIONCHECK.exe", "e-Trust Antivirus"},
	{"F-PROT.exe", "F-Prot AntiVirus"},
	{"f-prot95.exe", "已知杀软进程,名称暂未收录"},
	{"f-secure.exe", "冰岛"},
	{"fameh32.exe", "F-Secure"},
	{"fast.exe", " FastUsr"},
	{"fch32.exe", "F-Secure"},
	{"fih32.exe", "F-Secure"},
	{"findviru.exe", "F-Secure"},
	{"firesvc.exe", "McAfee"},
	{"firetray.exe", "McAfee"},
	{"FIREWALL.exe", "AshampooSoftware"},
	{"fnrb32.exe", "F-Secure"},
	{"FortiTray.exe", "飞塔"},
	{"fp-win.exe", " F-Prot Antivirus OnDemand"},
	{"FPROTTRAY.exe", "F-PROT Antivirus"},
	{"FPWIN.exe", "Verizon"},
	{"Frameworkservice.exe", "McAfee"},
	{"FRESHCLAM.exe", "ClamAV"},
	{"frminst.exe", "McAfee"},
	{"fsaa.exe", "F-Secure"},
	{"fsav.exe", "F-Secure"},
	{"FSAV32.exe", "F-Secure"},
	{"fsav530stbyb.exe", "F-Secure"},
	{"fsav530wtbyb.exe", "F-Secure"},
	{"fsav95.exe", "F-Secure"},
	{"fsavgui.exe", "F-Secure杀毒"},
	{"FSBWSYS.exe", "F-secure"},
	{"FSDFWD.exe", "F-Secure"},
	{"FSGK32.exe", "F-Secure"},
	{"FSGK32ST.exe", "F-Secure"},
	{"fsm32.exe", "F-Secure"},
	{"FSMA32.exe", "F-Secure"},
	{"FSMB32.exe", "F-Secure"},
	{"FSSM32.exe", "F-Secure"},
	{"FYFireWall.exe", "风云防火墙"},
	{"gbmenu.exe", "已知杀软进程,名称暂未收录"},
	{"GG.exe", "巨盾网游安全盾"},
	{"gov_defence_daemon.exe", "云锁"},
	{"gov_defence_service.exe", "云锁"},
	{"guard.exe", "ewido"},
	{"guarddog.exe", "ewido"},
	{"GUARDGUI.exe", "网游保镖"},
	{"GUARDNT.exe", "IKARUS"},
	{"hipstray.exe", "火绒"},
	{"HipsDaemon.exe", "火绒"},
	{"hipsvc.exe", "McAfee"},
	{"htlog.exe", "已知杀软进程,名称暂未收录"},
	{"htpatch.exe", "Silicon Integrated Systems Corporation"},
	{"hwpe.exe", "已知杀软进程,名称暂未收录"},
	{"hws.exe", "护卫神"},
	{"hws_ui.exe", "护卫神"},
	{"hwsd.exe", "护卫神"},
	{"HwsPanel.exe", "护卫神"},
	{"IAMAPP.exe", "Symantec"},
	{"iamserv.exe", "Symantec"},
	{"iamstats.exe", "Symantec"},
	{"iedriver.exe", " Urlblaze.com"},
	{"iface.exe", "Panda Antivirus Module"},
	{"infus.exe", "Infus Dialer"},
	{"infwin.exe", "Msviewparasite"},
	{"INOCIT.exe", "eTrust"},
	{"INORPC.exe", "eTrust"},
	{"INORT.exe", "eTrust"},
	{"INOTASK.exe", "eTrust"},
	{"INOUPTNG.exe", "eTrust"},
	{"intdel.exe", "Inet Delivery"},
	{"intren.exe", "已知杀软进程,名称暂未收录"},
	{"Iparmor.exe.exe", "木马克星"},
	{"iptray.exe", "Immunet杀毒"},
	{"ISAFE.exe", "eTrust"},
	{"jammer.exe", "已知杀软进程,名称暂未收录"},
	{"K7TSecurity.exe", "K7杀毒"},
	{"KAV.exe", "Kaspersky"},
	{"KAVMM.exe", "Kaspersky"},
	{"KAVPF.exe", "Kaspersky"},
	{"KAVPFW.exe", "Kaspersky"},
	{"KAVSTART.exe", "Kaspersky"},
	{"KAVSVC.exe", "Kaspersky"},
	{"KAVSVCUI.exe", "Kaspersky"},
	{"kazza.exe", "Kapersky"},
	{"keenvalue.exe", "EUNIVERSE INC"},
	{"KMAILMON.exe", "金山毒霸"},
	{"knsdtray.exe", "可牛杀毒"},
	{"kpfwtray.exe", "金山网镖"},
	{"ksafe.exe", "金山卫士"},
	{"KSafeSvc.exe", "金山毒霸"},
	{"KSafeTray.exe", "金山毒霸"},
	{"KSWebShield.exe", "金山网盾"},
	{"KvMonXP.exe", "江民杀毒"},
	{"KWatch.exe", "金山毒霸"},
	{"kxetray.exe", "金山毒霸"},
	{"launcher.exe", "Intercort Systems"},
	{"ldpro.exe", "已知杀软进程,名称暂未收录"},
	{"ldscan.exe", "Windows Trojans Inspector"},
	{"localnet.exe", "已知杀软进程,名称暂未收录"},
	{"luall.exe", "Symantec"},
	{"luau.exe", "Symantec"},
	{"lucomserver.exe", "Norton"},
	{"mcafeefire.exe", "McAfee"},
	{"MCAGENT.exe", "McAfee"},
	{"MCMNHDLR.exe", "McAfee"},
	{"MCREGWIZ.exe", "McAfee"},
	{"mcscript.exe", "McAfee"},
	{"mcscript_inuse.exe", "McAfee"},
	{"Mcshield.exe", "McAfee"},
	{"mctool.exe", "McAfee"},
	{"mctray.exe", "McAfee"},
	{"MCUPDATE.exe", "McAfee"},
	{"mcvsrte.exe", "McAfee"},
	{"MCVSSHLD.exe", "McAfee"},
	{"mfeann.exe", "McAfee"},
	{"mfevtps.exe", "McAfee"},
	{"mfin32.exe", "MyFreeInternetUpdate"},
	{"mfw2en.exe", "MyFreeInternetUpdate"},
	{"mfweng3.02d30.exe", "MyFreeInternetUpdate"},
	{"mgavrtcl.exe", "McAfee"},
	{"mgavrte.exe", "McAfee"},
	{"mghtml.exe", "McAfee"},
	{"mgui.exe", "BullGuard"},
	{"minilog.exe", "Zone Labs Inc"},
	{"mmod.exe", "EzulaInc"},
	{"MongoosaGUI.exe", "Mongoosa杀毒"},
	{"mostat.exe", "WurldMediaInc"},
	{"mpfagent.exe", "McAfee"},
	{"mpfservice.exe", "McAfee"},
	{"mpftray.exe", "McAfee"},
	{"MPMon.exe", "微点主动防御"},
	{"mscache.exe", "Integrated Search Technologies Spyware"},
	{"mscman.exe", "OdysseusMarketingInc"},
	{"msmgt.exe", "Total Velocity Spyware"},
	{"MsMpEng.exe", "Microsoft Security Essentials"},
	{"mssecess.exe", "微软杀毒"},
	{"msvxd.exe", "W32/Datom-A"},
	{"mwatch.exe", "已知杀软进程,名称暂未收录"},
	{"MYAGTSVC.exe", "McAfee"},
	{"MYAGTTRY.exe", "McAfee"},
	{"naprdmgr.exe", "McAfee"},
	{"nav.exe", "Reuters Limited"},
	{"navapsvc.exe", "Norton AntiVirus"},
	{"navapw32.exe", "Norton AntiVirus"},
	{"NAVLU32.exe", "Norton"},
	{"NAVW32.exe", "Norton Antivirus"},
	{"ndd32.exe", "诺顿磁盘医生"},
	{"neowatchlog.exe", "已知杀软进程,名称暂未收录"},
	{"NEOWATCHTRAY.exe", "NeoWatch"},
	{"netutils.exe", "已知杀软进程,名称暂未收录"},
	{"NISSERV.exe", "Norton"},
	{"NISUM.exe", "Norton"},
	{"NMAIN.exe", "Norton"},
	{"nod32.exe", "ESET Smart Security"},
	{"norton_internet_secu_3.0_407.exe", "已知杀软进程,名称暂未收录"},
	{"notstart.exe", "已知杀软进程,名称暂未收录"},
	{"NPFMntor.exe", "Norton杀毒软件"},
	{"NPFMSG.exe", "Norman个人防火墙"},
	{"NPROTECT.exe", "Symantec"},
	{"npscheck.exe", "Norton"},
	{"npssvc.exe", "Norton"},
	{"NSMDTR.exe", "Norton"},
	{"nspupsvc.exe", "nProtect杀毒"},
	{"ntrtscan.exe", "趋势反病毒应用程序"},
	{"nui.exe", "已知杀软进程,名称暂未收录"},
	{"OFCPFWSVC.exe", "OfficeScanNT"},
	{"ONLINENT.exe", "已知杀软进程,名称暂未收录"},
	{"OP_MON.exe", " OutpostFirewall"},
	{"otfix.exe", "已知杀软进程,名称暂未收录"},
	{"outpost.exe", "Outpost Firewall"},
	{"outpostinstall.exe", "Outpost"},
	{"parmor.exe", "木马克星"},
	{"patch.exe", "趋势科技"},
	{"PAVFIRES.exe", "熊猫卫士"},
	{"PAVFNSVR.exe", "熊猫卫士"},
	{"PAVKRE.exe", "熊猫卫士"},
	{"PAVPROT.exe", "熊猫卫士"},
	{"PAVPROXY.exe", "熊猫卫士"},
	{"PAVPRSRV.exe", "熊猫卫士"},
	{"PAVSRV51.exe", "熊猫卫士"},
	{"PAVSS.exe", "熊猫卫士"},
	{"pavw.exe", "已知杀软进程,名称暂未收录"},
	{"PCCGUIDE.exe", "PC-cillin"},
	{"PCCIOMON.exe", "PC-cillin"},
	{"PCCNTMON.exe", "PC-cillin"},
	{"PCCPFW.exe", "趋势科技"},
	{"PCCTLCOM.exe", "趋势科技"},
	{"pcscan.exe", "趋势科技"},
	{"PCTAV.exe", "PC Tools AntiVirus"},
	{"pdsetup.exe", "已知杀软进程,名称暂未收录"},
	{"PERSFW.exe", "Tiny Personal Firewall"},
	{"PERVAC.exe", "已知杀软进程,名称暂未收录"},
	{"PESTPATROL.exe", "Ikarus"},
	{"pfw.exe", "天网防火墙"},
	{"pgmonitr.exe", "PromulGate SpyWare"},
	{"pingscan.exe", "已知杀软进程,名称暂未收录"},
	{"platin.exe", "已知杀软进程,名称暂未收录"},
	{"pop3trap.exe", "PC-cillin"},
	{"poproxy.exe", "NortonAntiVirus"},
	{"popscan.exe", "已知杀软进程,名称暂未收录"},
	{"powerscan.exe", "Integrated Search Technologies"},
	{"ppinupdt.exe", "已知杀软进程,名称暂未收录"},
	{"pptbc.exe", "已知杀软进程,名称暂未收录"},
	{"ppvstop.exe", "已知杀软进程,名称暂未收录"},
	{"PREVSRV.exe", "熊猫卫士"},
	{"prizesurfer.exe", "Prizesurfer"},
	{"prmt.exe", "OpiStat"},
	{"prmvr.exe", "Adtomi"},
	{"processmonitor.exe", "Sysinternals"},
	{"proport.exe", "已知杀软进程,名称暂未收录"},
	{"protectx.exe", "ProtectX"},
	{"PSafeSysTray.exe", "PSafe杀毒"},
	{"pspf.exe", "已知杀软进程,名称暂未收录"},
	{"purge.exe", "已知杀软进程,名称暂未收录"},
	{"qconsole.exe", "Norton AntiVirus Quarantine Console"},
	{"QQPCRTP.exe", "QQ电脑管家"},
	{"QQPCTray.exe", "QQ电脑管家"},
	{"qserver.exe", "Norton Internet Security"},
	{"QUHLPSVC.exe", "QUICK HEAL杀毒"},
	{"rapapp.exe", "BlackICE"},
	{"RavMonD.exe", "瑞星杀毒"},
	{"rb32.exe", "RapidBlaster"},
	{"rcsync.exe", "PrizeSurfer"},
	{"realmon.exe", "Realmon "},
	{"remupd.exe", "熊猫卫士"},
	{"rescue.exe", "已知杀软进程,名称暂未收录"},
	{"rescue32.exe", "卡巴斯基互联网安全套装"},
	{"rfwmain.exe", "瑞星防火墙"},
	{"rshell.exe", "已知杀软进程,名称暂未收录"},
	{"rtvscan.exe", "诺顿杀毒"},
	{"rtvscn95.exe", "Real-time virus scanner "},
	{"rulaunch.exe", "McAfee User Interface"},
	{"run32dll.exe", "PAL PC Spy"},
	{"safeboxTray.exe", "360杀毒"},
	{"safedog.exe", "安全狗"},
	{"safedogguardcenter.exe", "安全狗"},
	{"SafeDogServerUI.exe", "安全狗"},
	{"SafeDogSiteIIS.exe", "安全狗"},
	{"SafeDogTray.exe", "安全狗"},
	{"safedogupdatecenter.exe", "安全狗"},
	{"safeweb.exe", "PSafe Tecnologia"},
	{"SAVADMINSERVICE.exe", "SAV"},
	{"SAVMAIN.exe", "SAV"},
	{"SavProgress.exe", "Sophos杀毒"},
	{"SAVSCAN.exe", "SAV"},
	{"SBAMSvc.exe", "VIPRE"},
	{"sbserv.exe", "Norton Antivirus"},
	{"scan32.exe", "McAfee"},
	{"sched.exe", "Avira(小红伞)"},
	{"scrscan.exe", "360杀毒"},
	{"SDHELP.exe", "Spyware Doctor"},
	{"sfc.exe", "System file checker"},
	{"sh.exe", "MKS Toolkit for Win3"},
	{"showbehind.exe", "MicroSmarts Enterprise Component "},
	{"SHSTAT.exe", "McAfee"},
	{"soap.exe", "System Soap Pro"},
	{"sofi.exe", "已知杀软进程,名称暂未收录"},
	{"SophosCleanM.exe", "Sophos杀毒"},
	{"SophosFS.exe", "Sophos杀毒"},
	{"SophosHealth.exe", "Sophos杀毒"},
	{"SophosSafestore64.exe", "Sophos杀毒"},
	{"SophosUI.exe", "Sophos杀毒"},
	{"SPBBCSVC.exe", "Symantec"},
	{"sperm.exe", "已知杀软进程,名称暂未收录"},
	{"SPHINX.exe", "SPHINX防火墙"},
	{"SPIDERCPL.exe", "Dr.Web"},
	{"SPIDERML.exe", "Dr.Web"},
	{"spidernt.exe", "Dr.web"},
	{"SPIDERUI.exe", "Dr.Web"},
	{"SPYBOTSD.exe", "Spybot "},
	{"SpywareTerminatorShield.exe", "SpywareTerminator反间谍软件"},
	{"supporter5.exe", "eScorcher反病毒"},
	{"SWAGENT.exe", "SonicWALL"},
	{"SWDOCTOR.exe", "SonicWALL"},
	{"SWNETSUP.exe", "Sophos"},
	{"SYMLCSVC.exe", "Symantec"},
	{"SYMPROXYSVC.exe", "Symantec"},
	{"SYMSPORT.exe", "Sysmantec"},
	{"symtray.exe", "Symantec"},
	{"SYMWSC.exe", "Sysmantec"},
	{"SYNMGR.exe", "Sysmantec"},
	{"Tbmon.exe", "McAfee"},
	{"tbscan.exe", "ThunderBYTE"},
	{"tc.exe", "TimeCalende"},
	{"titanin.exe", "TitanHide"},
	{"TMBMSRV.exe", "趋势杀毒"},
	{"TMLISTEN.exe", "趋势科技"},
	{"TMNTSRV.exe", "趋势科技"},
	{"TMPROXY.exe", "趋势科技"},
	{"TNBUTIL.exe", "Anti-Virus"},
	{"TrojanHunter.exe", "木马猎手"},
	{"tvmd.exe", "Total Velocity"},
	{"tvtmd.exe", " Total Velocity"},
	{"udaterui.exe", "McAfee"},
	{"UnThreat.exe", "UnThreat杀毒"},
	{"updaterui.exe", "McAfee"},
	{"usysdiag.exe", "火绒"},
	{"VBA32ECM.exe", "已知杀软进程,名称暂未收录"},
	{"VBA32IFS.exe", "已知杀软进程,名称暂未收录"},
	{"vba32lder.exe", "vb32杀毒"},
	{"VBA32PP3.exe", "已知杀软进程,名称暂未收录"},
	{"VCRMON.exe", "VirusChaser"},
	{"vettray.exe", "eTrust"},
	{"vir-help.exe", "已知杀软进程,名称暂未收录"},
	{"vnpc3000.exe", "已知杀软进程,名称暂未收录"},
	{"vpc32.exe", "Symantec"},
	{"vpc42.exe", "Symantec"},
	{"VRMONNT.exe", "HAURI"},
	{"VRMONSVC.exe", "HAURI"},
	{"VSHWIN32.exe", "McAfee"},
	{"vsmain.exe", "McAfee"},
	{"vsmon.exe", "Zone Alarm"},
	{"vsserv.exe", "比特梵德"},
	{"VSSTAT.exe", "McAfee"},
	{"vstskmgr.exe", "McAfee"},
	{"wfindv32.exe", "已知杀软进程,名称暂未收录"},
	{"wsctrl.exe", "火绒"},
	{"XCOMMSVR.exe", "BitDefender"},
	{"yunsuo_agent_daemon.exe", "云锁"},
	{"yunsuo_agent_service.exe", "云锁"},
	{"zapro.exe", "Zone Alarm"},
	{"ZhuDongFangYu.exe", "360安全卫士-主动防御"},
	{"ZONEALARM.exe", "Zone Alarm"},

		};
	    

	}
}
